---
- name: "Postgresql | Install additional packages"
  apt:
    name: "{{ postgresql_additional_packages }}"
    state: present
    update_cache: yes

- name: "Postgresql | Import the repository signing key"
  apt_key:
    url: "{{ postgresql_repo_key }}"
    state: present

- name: "Postgresql | Create the file repo config"
  apt_repository:
    repo: "{{ postgresql_repo }}"
    state: present
    filename: "{{ postgresql_repo_filename }}"

- name: "Postgresql | Install package"
  apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: yes

- include_tasks: initialize.yaml

- include_tasks: configure.yaml

- name: "Postgresql | Ensure Postgresql started and enabled"
  service: 
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: "{{ postgresql_service_enabled }}"

- name: "Postgresql | Check if standby.signal exists"
  stat:
    path: "{{ postgresql_data_dir }}/main/standby.signal"
  register: standby_signal_file

- name: "Postgresql | Setup postgres Master or Replica"
  include_tasks: 
    file: "{{ postgresql_role }}.yaml"
  when: not standby_signal_file.stat.exists
