---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: master1
    box: ubuntu/focal64
    interfaces:
      - network_name: private_network
        ip: 192.168.56.201
    groups:
      - master
  - name: replica1
    box: ubuntu/focal64
    interfaces:
      - network_name: private_network
        ip: 192.168.56.202
    groups:
      - replica
provisioner:
  name: ansible
verifier:
  name: ansible
